apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-app
  namespace: haste
spec:
  selector:
    matchLabels:
      app: image-processing-app
  replicas: 1
  template:
    metadata:
      name: test
      labels:
        app: image-processing-app
    spec:
      containers:
        - name: image-proc
          image: benblamey/image_analysis_container2:latest
#          command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          imagePullPolicy: Always # needed since we use 'latest' tag.
          volumeMounts:
            - mountPath: "/mnt/mikro-testdata"
              name: test-volume
          resources:
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: mikro-testdata-pvc
      restartPolicy: Always
