### set the default resource requests/limits for the namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: haste
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 250m
    type: Container