apiVersion: v1
kind: PersistentVolume
metadata:
  name: mikro-testdata-pv
  labels:
    storage: nfs-mikro-testdata
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.10.0.8
    path: "/mikro_testdata"


