# TODO: max 1 replica supported. there is no feature to set max no of replicas.
# to achieve this, clone the pvc, and set ReadWriteOnce access mode. (?)


apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-worker
  namespace: haste
spec:
  selector:
    matchLabels:
      app: pipeline-worker
  replicas: 1
  template:
    metadata:
      name: test
      labels:
        app: pipeline-worker
    spec:
      containers:
        - name: pipeline-worker
          image: benblamey/haste_pipeline_worker:latest
          args:
            - "--host"
            - haste-rabbitmq.haste.svc.cluster.local
            - "/mnt/mikro-testdata/source/" # path on disk
          imagePullPolicy: Always # we use 'latest' tag, always pull. note: need to delete and re-create deployment for it to happen!
          volumeMounts:
            - mountPath: "/mnt/mikro-testdata"
              name: test-volume
          resources:
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: mikro-testdata-pvc
      restartPolicy: Always
