apiVersion: v1
kind: PersistentVolume
metadata:
  name: haste-rabbitmq-pv
  labels:
    storage: nfs-haste-rabbitmq
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node
  nfs:
    server: 10.10.0.8
    path: "/Public/kube-pv/haste-rabbitmq"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  haste-rabbitmq-pvc
  namespace: haste
spec:
  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 8Gi
  # You need to specify this or else it tries default storageclass
  storageClassName: ''
  # Bind to the specific pv above
  selector:
    matchLabels:
      storage: nfs-haste-rabbitmq

