# See: https://github.com/helm/charts/tree/master/stable/mongodb


usePassword: false


# don't allocate this deployment on machines with GPU resources
nodeSelector:
  acceleration: none

# provide some extra time for the mongdb server to start up
livenessProbe:
  enabled: true
  initialDelaySeconds: 300

readinessProbe:
  enabled: true
  initialDelaySeconds: 300

# storage.
persistence:
  enabled: true
  existingClaim: haste-state-mongodb-pvc # use pre-existing PVC to persist data
