usePassword: false

resources: 
  limits:
    cpu: 4
    memory: 4G
  requests:
    cpu: 2
    memory: 2G

persistence:
  enabled: true
  existingClaim: haste-state-mongodb-pvc

  accessModes:
    - ReadWriteOnce
  size: 8Gi
