# See: https://github.com/helm/charts/tree/master/stable/mongodb


usePassword: false



# storage.
persistence:
  enabled: true
  existingClaim: haste-state-mongodb-pvc # use pre-existing PVC to persist data

  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node
  size: 8Gi
