usePassword: false

resources: 
  limits:
    cpu: 4
    memory: 4G
  requests:
    cpu: 1
    memory: 1G

persistence:
  enabled: true

  accessModes:
    - ReadWriteOnce # the volume can be mounted as read-write by a single node
  size: 8Gi
