# TODO: max 1 replica supported. there is no feature to set max no of replicas.
# to achieve this, clone the pvc, and set ReadWriteOnce access mode. (?)

# this is the 'old' one?


apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-app
  namespace: haste
spec:
  selector:
    matchLabels:
      app: image-processing-app
  replicas: 1
  template:
    metadata:
      name: test
      labels:
        app: image-processing-app
    spec:
      containers:
        - name: image-proc
          image: benblamey/image_analysis_container2:latest
#          command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          imagePullPolicy: Always # we use 'latest' tag, always pull. note: need to delete and re-create deployment for it to happen!
          volumeMounts:
            - mountPath: "/mnt/mikro-testdata"
              name: test-volume
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: mikro-testdata-pvc
      restartPolicy: Always
